// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlTSwNAoA015GEr4fkcgUGQDY0JhDM9WU',
    appId: '1:874432384266:web:4ac438bb7782fabebdfef3',
    messagingSenderId: '874432384266',
    projectId: 'event-reminder-2025',
    authDomain: 'event-reminder-2025.firebaseapp.com',
    storageBucket: 'event-reminder-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ZjgKWi5wGMSSZlA_CMZXRG7zwdz4GF8',
    appId: '1:874432384266:android:6edd6aba3ae3ee76bdfef3',
    messagingSenderId: '874432384266',
    projectId: 'event-reminder-2025',
    storageBucket: 'event-reminder-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQsDTDxqaGOvtuduq4kzTEtAz9jyhPaI',
    appId: '1:874432384266:ios:8f4e7bd24c95b3c8bdfef3',
    messagingSenderId: '874432384266',
    projectId: 'event-reminder-2025',
    storageBucket: 'event-reminder-2025.firebasestorage.app',
    iosBundleId: 'com.example.eventReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQsDTDxqaGOvtuduq4kzTEtAz9jyhPaI',
    appId: '1:874432384266:ios:8f4e7bd24c95b3c8bdfef3',
    messagingSenderId: '874432384266',
    projectId: 'event-reminder-2025',
    storageBucket: 'event-reminder-2025.firebasestorage.app',
    iosBundleId: 'com.example.eventReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlTSwNAoA015GEr4fkcgUGQDY0JhDM9WU',
    appId: '1:874432384266:web:05aadf894914eda9bdfef3',
    messagingSenderId: '874432384266',
    projectId: 'event-reminder-2025',
    authDomain: 'event-reminder-2025.firebaseapp.com',
    storageBucket: 'event-reminder-2025.firebasestorage.app',
  );
}
